### ISSUE TITLE
Jv

### ISSUE THREAD

**Issue by waleady** [waleady/generate-random-otp#1]

**Comment by waleady** [comment]
Delta Group

**Comment by PooNanyChiefPriest** [comment]
create a repo link for joining

**Comment by Tahiraminu** [comment]
Hi

**Comment by PooNanyChiefPriest** [comment]
@Tahiraminu @waleady Who else is facing difficulty with this thing

**Comment by rikhaleel** [comment]
Hi

**Comment by waleady** [comment]
What's the problem that you're facing ?

**Comment by waleady** [comment]
> What's the problem that you're facing ?

@PooNanyChiefPriest

**Comment by Yogishor** [comment]
Hi
